GET http://localhost:5177/genres


###
GET http://localhost:5177/genres/11


###
POST http://localhost:5177/genres
Content-Type: application/json

{
    "name": "Some new genre"
}


###
PUT http://localhost:5177/genres/11
Content-Type: application/json

{
    "name": "Romance"
}


###
DELETE http://localhost:5177/genres/13